### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by MeggyCal** [moremoban/gitfs2#7]
Could you please add LICENSE file (or similar) with a license statement? It is needed for us to get this package into our distribution.

**Comment by chfw** [comment]
Please stay tuned for next release. it should be this week.

**Comment by chfw** [comment]
Released.

**Comment by chfw** [comment]
moban 0.7.0 have dropped the compulsory dependencies on gitfs2 and pypifs.

**Comment by MeggyCal** [comment]
you are perfect :1st_place_medal: thanks for notifying me, we still have some problems with few tests (to be honest, I had problems also with tests on this package), but this will help :+1:
